### ISSUE TITLE
Error when pushing the Datacore app to the dashboard of an user

### ISSUE THREAD

**Issue by bobeal** [ozwillo/ozwillo-portal#322] opened 2015-11-15 07:38 UTC
Reported from @OzBruno : 

```
java.lang.NullPointerException 
org.oasis_eu.portal.front.my.appsmanagement.MyAppsAJAXServices.lambda$getUsersForInstance$193(MyAppsAJAXServices.java:92)
org.oasis_eu.portal.front.my.appsmanagement.MyAppsAJAXServices$$Lambda$230/1086786827.test(Unknown Source) java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1359)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
org.oasis_eu.portal.front.my.appsmanagement.MyAppsAJAXServices.getUsersForInstance(MyAppsAJAXServices.java:92) 
```

**Comment by mdutoo** [comment] 2015-11-15 14:25
Duplicate of #293 (Kernel data should be cleaned, portal should check it, and long term solution #238 ).

**Closed** 2015-11-15 14:43 UTC
Labels: apps management, bug, duplicate, high priority
